#!/bin/bash

#
# CONFIG
#

# Container
CONTAINER=${TERMINUS_CONTAINER:-terminus-server}
REPOSITORY=${TERMINUS_REPOSITORY:-terminusdb/terminus-server}
TAG=${TERMINUS_TAG:-latest} 

# Volumes
TERMINUS_STORAGE=${TERINUS_TERMINUS_STORAGE:-terminus_storage}
TERMINUS_CONFIG=${TERMINUS_TERMINUS_CONFIG:-terminus_config}
STORAGE_VOLUME=${TERMINUS_STORAGE_VOLUME:-/app/terminusdb/storage}
CONFIG_VOLUME=${TERMINUS_CONFIG_VOLUME:-/app/terminusdb/config}

# Server
SCHEME=${TERMINUS_SCHEME:-http}
SERVER=${TERMINUS_SERVER:-localhost}
SERVER_PORT=${TERMINUS_SERVER_PORT:-6363}
PORT=${TERMINUS_PORT:-6363}
WORKERS=${TERMINUS_WORKERS:-8}
PASS=${TERMINUS_PASS:-root}
CONSOLE=${TERMINUS_CONSOLE:-$SCHEME://$SERVER:$PORT/console}

if command -v sudo >/dev/null;
then
  DOCKER=${TERMINUS_DOCKER:-sudo docker}
else
  DOCKER=${TERMINUS_DOCKER:-docker}
fi

if [[ -z "$TERMINUS_PUBLIC_URL" ]];
then
  SET_PUBLIC=""
 else
  SET_PUBLIC="-e PUBLIC_URL=\"$TERMINUS_PUBLIC_URL\""
fi

if [[ -z "$TERMINUS_LOCAL" ]];
then
  MOUNT_LOCAL=""
 else
  MOUNT_LOCAL="-v \"$TERMINUS_LOCAL\":/app/local_files"
  printf "\nMOUNT \"%s\" \nTO \"/app/local_files\"\n" "$TERMINUS_LOCAL"
fi


#
# FUNCTIONS
#

_usage () {
  printf "\
USAGE:
  terminus-container [COMMAND]

  help      show usage
  run       run container
  stop      stop container
  console   launch console in web browser
  attach    attach to prolog shell
  stats     show container stats
  rm        remove volumes\n"
}

_confirm() {
  read -r -p "Are you sure? [y/N] " RESPONSE
  case "$RESPONSE" in
      [yY][eE][sS]|[yY]) 
          return 0
      ;;
      *)
          return 1
      ;;
  esac
  printf "\n"
}

_run () {
  if [[ $TAG == "latest" || $TAG == "dev" ]];
  then
    $DOCKER image rm "$REPOSITORY:$TAG" 2>/dev/null
  fi
  eval "$DOCKER" run -d -it --rm \
    --name "$CONTAINER" -p "$PORT:$SERVER_PORT" \
    -v "$TERMINUS_STORAGE:$STORAGE_VOLUME:rw" \
    -v "$TERMINUS_CONFIG:$CONFIG_VOLUME:rw" \
    "$MOUNT_LOCAL" \
    "$SET_PUBLIC" \
    -e SERVER_NAME="$SERVER" \
    -e SERVER_PORT="$SERVER_PORT" \
    -e WORKERS="$WORKERS" \
    -e ADMIN_PASS="$PASS" \
    "$REPOSITORY:$TAG"
}

_stop () {
  $DOCKER stop "$CONTAINER"
}

_restart () {
  $DOCKER stop "$CONTAINER"
}

_attach () {
  $DOCKER attach "$CONTAINER"
}

_stats () {
  $DOCKER stats "$CONTAINER"
}

_rm () {
 if _confirm
 then
   $DOCKER volume rm "$TERMINUS_STORAGE" \
   && $DOCKER volume rm "$TERMINUS_CONFIG"
 fi
}

_console () {

if command -v python >/dev/null;
then
  python -m webbrowser "$CONSOLE"
else
  printf "\nopen %s in your browser\n" "$CONSOLE"
fi
}

_serve () {
if command -v python >/dev/null;
then
  python -m http.server 8888
else
  printf "\npython is required for this feature\n"
fi
}

#
# PROCESS ARGS
#

printf "\n"

if [ -n "$1" ]; then
  case "$1" in
    "run")
      # _build
      _run > /dev/null \
        && printf "terminus-server container started %s\n" "$CONSOLE" \
        || printf "\nIs the container already running?\n"
    ;;
    "stop")
      _stop > /dev/null \
        && printf "terminus-server container stopped\n" \
        || printf "\nIs the container running?\n"
    ;;
    "console")
      _console \
        || printf "this command requires python\n"
    ;;
    "attach")
      printf "Ctrl+p Ctrl+q to detach\n\n"
      _attach
    ;;
    "stats")
      _stats \
        || printf "\nIs the container running?\n"
    ;;
    "rm")
      printf "removing will delete storage and config volumes\n"
      _rm \
        || printf "\nIs the container stopped?\n"
    ;;
    "help")
      _usage
    ;;
    "serve")
      _serve
    ;;
    *)
      printf "invalid command\n\n"
      _usage
    ;;
  esac
else
  _usage
fi

printf "\n"

# vim:ft=sh
