name: CI

on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      TERMINUSDB_SUDO: ""

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install expect
        run: sudo apt-get install expect

      - name: Install bats for testing
        run: sudo npm install -g bats

      - name: Run shellcheck
        run: shellcheck ./terminusdb-container

      - run: sudo docker

      - name: Run tests with bats
        run: bats .ci/tests/basic.bats
